name: ci

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    env:
      PYTHONUNBUFFERED: "1"
      FEEDFLIP_OFFLINE: "1"
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-lock.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (lockfile preferred)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-lock.txt ]; then
            pip install -r requirements-lock.txt
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "ERROR: no requirements-lock.txt or requirements.txt found"; exit 1
          fi

      - name: Lint (ruff + black)
        run: |
          ruff --version || pip install ruff
          black --version || pip install black
          ruff check .
          black --check .

      - name: Run tests (offline coverage)
        run: |
          pytest -m "not network" --cov=feedflipnets --cov-report=term-missing --cov-fail-under=60

      - name: Micro-benchmark (offline, numpy-only)
        run: |
          python scripts/bench_micro.py --seeds 123 124 125 --steps 64 --out .artifacts/bench

      - name: Determinism check (run twice; hashes must match)
        run: |
          sha256sum .artifacts/bench/bench_micro.csv .artifacts/bench/bench_micro.md > .artifacts/hash1.txt
          python scripts/bench_micro.py --seeds 123 124 125 --steps 64 --out .artifacts/bench
          sha256sum .artifacts/bench/bench_micro.csv .artifacts/bench/bench_micro.md > .artifacts/hash2.txt
          diff -u .artifacts/hash1.txt .artifacts/hash2.txt

      - name: Attach benchmark to Step Summary
        run: |
          {
            echo "## FeedFlipNets Micro-Benchmark";
            echo;
            cat .artifacts/bench/bench_micro.md;
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bench-micro-${{ matrix.python-version }}
          path: |
            .artifacts/bench/bench_micro.md
            .artifacts/bench/bench_micro.csv
            .artifacts/bench/results.jsonl
