name: CI

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Bootstrap environment
        run: make bootstrap
      - name: Lint
        run: make lint
      - name: Run tests
        run: make test
      - name: Smoke test
        run: make smoke
      - name: Archive smoke artifacts
        run: |
          tar -czf smoke-${{ matrix.python-version }}.tar.gz runs/basic-dfa-cpu || true
      - uses: actions/upload-artifact@v3
        with:
          name: smoke-${{ matrix.python-version }}
          path: smoke-${{ matrix.python-version }}.tar.gz
